import type { Metadata } from "next";
import "./globals.css";
import { ClientProviders } from "@/components/ClientProviders";
import { Navigation } from "@/components/Navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body className="font-maplestory antialiased pt-16">
        <Navigation />
        <ClientProviders>{children}</ClientProviders>
      </body>
    </html>
  );
}
